### ISSUE TITLE
Plugin Crashes in IntelliJ "Cannot fetch remote documentation: internal error"

### ISSUE THREAD

**Issue by SHenckel** [Abnaxos/markdown-doclet#82]
This happens when I install the plugin and enable it for the project, then open javadoc quickviewer in the project.

This is the logfile entry:

2017-08-04 10:26:21,136 [ 850482]   INFO - mentation.DocumentationManager -  
java.lang.NullPointerException
	at ch.raffael.mddoclet.MarkdownDoclet.printError(MarkdownDoclet.java:451)
	at ch.raffael.mddoclet.mdtaglet.MarkdownTaglets$ErrorHandlerImpl.afterOptionsSetError(MarkdownTaglets.java:264)
	at ch.raffael.mddoclet.mdtaglet.MarkdownTaglets.doInitExecutor(MarkdownTaglets.java:166)
	at ch.raffael.mddoclet.mdtaglet.MarkdownTaglets.apply(MarkdownTaglets.java:148)
	at ch.raffael.mddoclet.Options.renderMarkdownTags(Options.java:520)
	at ch.raffael.mddoclet.Options.toHtml(Options.java:508)
	at ch.raffael.mddoclet.MarkdownDoclet.toHtml(MarkdownDoclet.java:436)
	at ch.raffael.mddoclet.integrations.idea.DocCommentProcessor.processDocComment(DocCommentProcessor.java:243)
	at ch.raffael.mddoclet.integrations.idea.MarkdownJavaDocInfoGenerator.generateCommonSection(MarkdownJavaDocInfoGenerator.java:48)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.a(JavaDocInfoGenerator.java:487)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateDocInfoCore(JavaDocInfoGenerator.java:368)
	at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateDocInfo(JavaDocInfoGenerator.java:418)
	at ch.raffael.mddoclet.integrations.idea.MarkdownDocumentationProvider.generateDoc(MarkdownDocumentationProvider.java:139)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector.a(DocumentationManager.java:1136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:90)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:146)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:90)
	at com.intellij.codeInsight.documentation.QuickDocUtil.runInReadActionWithWriteActionPriorityWithRetries(QuickDocUtil.java:96)
	at com.intellij.codeInsight.documentation.DocumentationManager$DefaultDocumentationCollector.getDocumentation(DocumentationManager.java:1134)
	at com.intellij.codeInsight.documentation.DocumentationManager.a(DocumentationManager.java:720)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.util.Alarm$Request.run(Alarm.java:395)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-08-04 10:27:31,821 [ 921167]   INFO - ide.actions.ShowFilePathAction - 
Exit code 1

**Comment by holysky5** [comment]
+1

**Comment by chitayta** [comment]
I faced the same issue with @SHenckel. Is there any update and solution for this issue?

**Comment by ericwork2008** [comment]
same issue

**Comment by eamell** [comment]
Same issue with 2020.2.1

**Comment by blague** [comment]
+1

**Comment by LeonMarino1** [comment]
Must be the problem that IntelliJ does not have tools.jar in the classpath, but after that still is not working with no further information from IntelliJ.
